# Generated by Django 2.1.5 on 2019-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskApp', '0002_auto_20190422_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpdeskRequestSLAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EM_0_AfterHrs', models.IntegerField(null=True)),
                ('EM_0_AfterMin', models.IntegerField(null=True)),
                ('EM_0_Name', models.CharField(max_length=100, null=True)),
                ('EM_0_To', models.CharField(max_length=100, null=True)),
                ('EM_1_AfterHrs', models.IntegerField(null=True)),
                ('EM_1_AfterMin', models.IntegerField(null=True)),
                ('EM_1_Name', models.CharField(max_length=100, null=True)),
                ('EM_1_To', models.CharField(max_length=100, null=True)),
                ('EM_2_AfterHrs', models.IntegerField(null=True)),
                ('EM_2_AfterMin', models.IntegerField(null=True)),
                ('EM_2_Name', models.CharField(max_length=100, null=True)),
                ('EM_2_To', models.CharField(max_length=100, null=True)),
                ('FulfillerExecutive', models.CharField(max_length=100, null=True)),
                ('HelpdeskCategory', models.CharField(max_length=100, null=True)),
                ('HelpdeskDepartment', models.CharField(max_length=100, null=True)),
                ('HelpdeskLocation', models.CharField(max_length=100, null=True)),
                ('HelpdeskPriority', models.CharField(max_length=100, null=True)),
                ('HelpdeskSubCategory', models.CharField(max_length=100, null=True)),
                ('ReminderMechanism', models.CharField(max_length=100, null=True)),
                ('TATHrs', models.IntegerField(null=True)),
                ('TATMins', models.IntegerField(null=True)),
            ],
        ),
    ]
