# Generated by Django 2.1.5 on 2019-04-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskApp', '0003_helpdeskrequestslas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='FulfillmentCompletedDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
