# Generated by Django 2.1.5 on 2019-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskApp', '0004_auto_20190429_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='WorkflowModifiedOn',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
