# Generated by Django 2.1.5 on 2019-04-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskApp', '0005_auto_20190429_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='OnBehalfUser',
            new_name='Escalation',
        ),
    ]
