# Generated by Django 2.1.5 on 2019-04-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskApp', '0006_auto_20190429_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='Escalation',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='Escalations',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
