# Generated by Django 2.1.5 on 2019-04-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskApp', '0008_auto_20190429_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='Escalation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
