# Generated by Django 2.1.5 on 2019-04-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskApp', '0009_helprequest_escalation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='Escalation',
        ),
    ]
