# Generated by Django 2.1.5 on 2019-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskApp', '0010_remove_helprequest_escalation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='InActive',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
    ]
